server:
  port: 8080
spring:
  application:
    name: kronocash-service
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-cold-thunder-a52h17fy.us-east-2.aws.neon.tech:5432/kronocash
    username: abhilashp44
    password: d4XtOYr3vuBn
    flyway:
      enabled: true
      locations: classpath:db/migration/postgresql
      schemas: kronocash
      baseline-on-migrate: true
      url: jdbc:postgresql://ep-cold-thunder-a52h17fy.us-east-2.aws.neon.tech:5432/kronocash
      user: abhilashp44
      password: d4XtOYr3vuBn
      driverClassName: org.postgresql.Driver
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-xokjpwctwfjktg8f.us.auth0.com/
          audience: http://kronocash-service
